#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 30 17:42:55 CET 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_pulse_gen_time_impl -key {Post-Implementation:sim_1:Timing:test_pulse_gen} -tclbatch test_pulse_gen.tcl -log simulate.log"
xsim test_pulse_gen_time_impl -key {Post-Implementation:sim_1:Timing:test_pulse_gen} -tclbatch test_pulse_gen.tcl -log simulate.log

